# https://github.com/hdecoded/media-server
#
# Services
#   Heimdall        - Dashboard
#   Plex            - Media player
#   Transmisison    - Torrent downloader client
#   Sonarr          - Searches for TV shows to download
#   Radarr          - Searches for movies to download
#   LazyLibrarian   - Searches for books to download
#   Ombi            - Allows users to request shows/movies to add to Plex/Sonarr/Radarr
#   Jackett         - Allows Sonarr/Radarr to search torrent trackers

version: '3'

services:

# Heimdall

    heimdall:
        image: ghcr.io/linuxserver/heimdall
        container_name: heimdall
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        volumes:
            - /mnt/media/docker/heimdall/config:/config
        ports:
            - 80:80
            - 443:443
        restart: unless-stopped

# Plex

    plex:
        image: ghcr.io/linuxserver/plex:latest
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            # - TZ=Asia/Kolkata
            - VERSION=docker
            - PLEX_CLAIM= #optional
        volumes:
            - /mnt/media/docker/plex/config:/config
            - /mnt/media/docker/plex/apsw.so:/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/lib-dynload/apsw.so # remove if you are not using trakt scrobller
            - /mnt/media/tvseries:/tv
            - /mnt/media/movies:/movies
            - /mnt/media/Java:/java
        restart: always

# Transmission

    transmission:
        image: ghcr.io/linuxserver/transmission
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
        volumes:
            - /mnt/media/docker/transmission/config:/config
            - /mnt/media/downloads:/downloads
            - /mnt/media/docker/transmission/watch:/watch
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        restart: unless-stopped

# Sonarr

    sonarr:
        image: ghcr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        volumes:
            - /mnt/media/docker/sonarr/config:/config
            - /mnt/media/tvseries:/tv
            - /mnt/media/downloads:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped

# Radarr

    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        volumes:
            - /mnt/media/docker/radarr/config:/config
            - /mnt/media/movies:/movies
            - /mnt/media/downloads:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped

# LazyLibrarian

    lazylibrarian:
        image: ghcr.io/linuxserver/lazylibrarian
        container_name: lazylibrarian
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
        volumes:
            - /mnt/media/docker/lazylibrarian/config:/config
            - /mnt/media/downloads:/downloads
            - /mnt/media/books:/books
        ports:
            - 5299:5299
        restart: unless-stopped

# Ombi

    ombi:
        image: ghcr.io/linuxserver/ombi
        container_name: ombi
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - BASE_URL=/ombi #optional
        volumes:
            - /mnt/media/docker/ombi/config:/config
        ports:
            - 3579:3579
        restart: unless-stopped

# Jackett

    jackett:
        image: ghcr.io/linuxserver/jackett
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - AUTO_UPDATE=true #optional
            - RUN_OPTS=<run options here> #optional
        volumes:
            - /mnt/media/docker/jackett/config:/config
            - /mnt/media/docker/jackett/downloads:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped


